version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL}
    env_file:
      - .env